// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/adapter.proto

package voltha // import "github.com/opencord/voltha-protos/protos/voltha"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import common "github.com/opencord/voltha-protos/protos/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdapterConfig struct {
	// Common adapter config attributes here
	LogLevel common.LogLevel_LogLevel `protobuf:"varint,1,opt,name=log_level,json=logLevel,proto3,enum=voltha.LogLevel_LogLevel" json:"log_level,omitempty"`
	// Custom (vendor-specific) configuration attributes
	AdditionalConfig     *any.Any `protobuf:"bytes,64,opt,name=additional_config,json=additionalConfig,proto3" json:"additional_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdapterConfig) Reset()         { *m = AdapterConfig{} }
func (m *AdapterConfig) String() string { return proto.CompactTextString(m) }
func (*AdapterConfig) ProtoMessage()    {}
func (*AdapterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_adapter_4b7bf3ace0adeff8, []int{0}
}
func (m *AdapterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdapterConfig.Unmarshal(m, b)
}
func (m *AdapterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdapterConfig.Marshal(b, m, deterministic)
}
func (dst *AdapterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdapterConfig.Merge(dst, src)
}
func (m *AdapterConfig) XXX_Size() int {
	return xxx_messageInfo_AdapterConfig.Size(m)
}
func (m *AdapterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AdapterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AdapterConfig proto.InternalMessageInfo

func (m *AdapterConfig) GetLogLevel() common.LogLevel_LogLevel {
	if m != nil {
		return m.LogLevel
	}
	return common.LogLevel_DEBUG
}

func (m *AdapterConfig) GetAdditionalConfig() *any.Any {
	if m != nil {
		return m.AdditionalConfig
	}
	return nil
}

// Adapter (software plugin)
type Adapter struct {
	// Unique name of adapter, matching the python packate name under
	// voltha/adapters.
	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vendor  string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Adapter configuration
	Config *AdapterConfig `protobuf:"bytes,16,opt,name=config,proto3" json:"config,omitempty"`
	// Custom descriptors and custom configuration
	AdditionalDescription *any.Any `protobuf:"bytes,64,opt,name=additional_description,json=additionalDescription,proto3" json:"additional_description,omitempty"`
	LogicalDeviceIds      []string `protobuf:"bytes,4,rep,name=logical_device_ids,json=logicalDeviceIds,proto3" json:"logical_device_ids,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Adapter) Reset()         { *m = Adapter{} }
func (m *Adapter) String() string { return proto.CompactTextString(m) }
func (*Adapter) ProtoMessage()    {}
func (*Adapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_adapter_4b7bf3ace0adeff8, []int{1}
}
func (m *Adapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adapter.Unmarshal(m, b)
}
func (m *Adapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adapter.Marshal(b, m, deterministic)
}
func (dst *Adapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adapter.Merge(dst, src)
}
func (m *Adapter) XXX_Size() int {
	return xxx_messageInfo_Adapter.Size(m)
}
func (m *Adapter) XXX_DiscardUnknown() {
	xxx_messageInfo_Adapter.DiscardUnknown(m)
}

var xxx_messageInfo_Adapter proto.InternalMessageInfo

func (m *Adapter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Adapter) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Adapter) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Adapter) GetConfig() *AdapterConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Adapter) GetAdditionalDescription() *any.Any {
	if m != nil {
		return m.AdditionalDescription
	}
	return nil
}

func (m *Adapter) GetLogicalDeviceIds() []string {
	if m != nil {
		return m.LogicalDeviceIds
	}
	return nil
}

type Adapters struct {
	Items                []*Adapter `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Adapters) Reset()         { *m = Adapters{} }
func (m *Adapters) String() string { return proto.CompactTextString(m) }
func (*Adapters) ProtoMessage()    {}
func (*Adapters) Descriptor() ([]byte, []int) {
	return fileDescriptor_adapter_4b7bf3ace0adeff8, []int{2}
}
func (m *Adapters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adapters.Unmarshal(m, b)
}
func (m *Adapters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adapters.Marshal(b, m, deterministic)
}
func (dst *Adapters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adapters.Merge(dst, src)
}
func (m *Adapters) XXX_Size() int {
	return xxx_messageInfo_Adapters.Size(m)
}
func (m *Adapters) XXX_DiscardUnknown() {
	xxx_messageInfo_Adapters.DiscardUnknown(m)
}

var xxx_messageInfo_Adapters proto.InternalMessageInfo

func (m *Adapters) GetItems() []*Adapter {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*AdapterConfig)(nil), "voltha.AdapterConfig")
	proto.RegisterType((*Adapter)(nil), "voltha.Adapter")
	proto.RegisterType((*Adapters)(nil), "voltha.Adapters")
}

func init() {
	proto.RegisterFile("voltha_protos/adapter.proto", fileDescriptor_adapter_4b7bf3ace0adeff8)
}

var fileDescriptor_adapter_4b7bf3ace0adeff8 = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x86, 0x49, 0xbc, 0x46, 0x1d, 0xb9, 0xf7, 0xda, 0xa1, 0x96, 0x68, 0x91, 0x06, 0xa1, 0x90,
	0x45, 0x4d, 0xd0, 0x42, 0xd7, 0xd5, 0xba, 0x29, 0xb8, 0xca, 0xb2, 0x9b, 0x10, 0x33, 0x63, 0x1c,
	0x98, 0xcc, 0x09, 0x49, 0x0c, 0xf8, 0x0a, 0xdd, 0xf5, 0xc1, 0xfa, 0x1e, 0x7d, 0x82, 0xae, 0x8b,
	0x33, 0x93, 0xaa, 0x5d, 0x74, 0x95, 0x39, 0xff, 0x77, 0xce, 0xfc, 0xff, 0x09, 0x83, 0xae, 0x2b,
	0xe0, 0xe5, 0x36, 0x0a, 0xb3, 0x1c, 0x4a, 0x28, 0xfc, 0x88, 0x44, 0x59, 0x49, 0x73, 0x4f, 0x96,
	0xd8, 0x52, 0x70, 0x38, 0x48, 0x00, 0x12, 0x4e, 0x7d, 0xa9, 0xae, 0x77, 0x1b, 0x3f, 0x12, 0x7b,
	0xd5, 0x32, 0x1c, 0x9e, 0xcf, 0xc7, 0x90, 0xa6, 0x20, 0x34, 0xb3, 0xcf, 0x59, 0x4a, 0xcb, 0x48,
	0x91, 0xf1, 0xab, 0x81, 0xfe, 0xce, 0x95, 0xd5, 0x13, 0x88, 0x0d, 0x4b, 0xf0, 0x03, 0xea, 0x70,
	0x48, 0x42, 0x4e, 0x2b, 0xca, 0x6d, 0xc3, 0x31, 0xdc, 0x7f, 0xb3, 0x81, 0xa7, 0xe6, 0xbd, 0x15,
	0x24, 0xab, 0x83, 0xfe, 0x7d, 0x08, 0xda, 0x5c, 0x9f, 0xf0, 0x1c, 0x5d, 0x44, 0x84, 0xb0, 0x92,
	0x81, 0x88, 0x78, 0x18, 0xcb, 0xcb, 0xec, 0x47, 0xc7, 0x70, 0xbb, 0xb3, 0x4b, 0x4f, 0xc5, 0xf6,
	0xea, 0xd8, 0xde, 0x5c, 0xec, 0x83, 0xde, 0xb1, 0x5d, 0x59, 0x8f, 0xdf, 0x4c, 0xd4, 0xd2, 0x61,
	0x70, 0x1f, 0x99, 0x8c, 0x48, 0xff, 0xce, 0xa2, 0xf9, 0xf1, 0xf9, 0x3e, 0x32, 0x02, 0x93, 0x11,
	0x3c, 0x42, 0x56, 0x45, 0x05, 0x81, 0xdc, 0x36, 0x4f, 0x91, 0x16, 0xf1, 0x0d, 0x6a, 0x55, 0x34,
	0x2f, 0x18, 0x08, 0xbb, 0x71, 0xca, 0x6b, 0x15, 0x4f, 0x90, 0xa5, 0xa3, 0xf5, 0x64, 0xb4, 0x7e,
	0xbd, 0xda, 0xd9, 0x4f, 0x08, 0x74, 0x13, 0x0e, 0xd0, 0xd5, 0xc9, 0x52, 0x84, 0x16, 0x71, 0xce,
	0xb2, 0x43, 0xf5, 0xdb, 0x66, 0xb5, 0x69, 0xff, 0x38, 0xba, 0x3c, 0x4e, 0xe2, 0x3b, 0x84, 0x39,
	0x24, 0x2c, 0x96, 0x17, 0x56, 0x2c, 0xa6, 0x21, 0x23, 0x85, 0xfd, 0xc7, 0x69, 0xb8, 0x9d, 0xa0,
	0xa7, 0xc9, 0x52, 0x82, 0x67, 0x52, 0x8c, 0xa7, 0xa8, 0xad, 0xa3, 0x15, 0xf8, 0x16, 0x35, 0x59,
	0x49, 0xd3, 0xc2, 0x36, 0x9c, 0x86, 0xdb, 0x9d, 0xfd, 0xff, 0x91, 0x3d, 0x50, 0x74, 0x31, 0x7d,
	0xf1, 0x13, 0x56, 0x6e, 0x77, 0x6b, 0x2f, 0x86, 0xd4, 0x87, 0x8c, 0x8a, 0x18, 0x72, 0xe2, 0xab,
	0xe6, 0x89, 0x7e, 0x03, 0xfa, 0xa3, 0xc4, 0xb5, 0x25, 0xcb, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x56, 0x4e, 0x83, 0xed, 0x85, 0x02, 0x00, 0x00,
}
