# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voltha_protos/ponsim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from voltha_protos import openflow_13_pb2 as voltha__protos_dot_openflow__13__pb2
try:
  voltha__protos_dot_yang__options__pb2 = voltha__protos_dot_openflow__13__pb2.voltha__protos_dot_yang__options__pb2
except AttributeError:
  voltha__protos_dot_yang__options__pb2 = voltha__protos_dot_openflow__13__pb2.voltha_protos.yang_options_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='voltha_protos/ponsim.proto',
  package='voltha',
  syntax='proto3',
  serialized_options=_b('Z+github.com/opencord/voltha-protos/go/voltha'),
  serialized_pb=_b('\n\x1avoltha_protos/ponsim.proto\x12\x06voltha\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fvoltha_protos/openflow_13.proto\">\n\x13PonSimOnuDeviceInfo\x12\x10\n\x08uni_port\x18\x01 \x01(\x05\x12\x15\n\rserial_number\x18\x02 \x01(\t\"O\n\x10PonSimDeviceInfo\x12\x10\n\x08nni_port\x18\x01 \x01(\x05\x12)\n\x04onus\x18\x02 \x03(\x0b\x32\x1b.voltha.PonSimOnuDeviceInfo\"E\n\tFlowTable\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12*\n\x05\x66lows\x18\x02 \x03(\x0b\x32\x1b.openflow_13.ofp_flow_stats\"<\n\x0bPonSimFrame\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x10\n\x08out_port\x18\x03 \x01(\x05\"2\n\x13PonSimPacketCounter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"T\n\x11PonSimPortMetrics\x12\x11\n\tport_name\x18\x01 \x01(\t\x12,\n\x07packets\x18\x02 \x03(\x0b\x32\x1b.voltha.PonSimPacketCounter\"K\n\rPonSimMetrics\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12*\n\x07metrics\x18\x02 \x03(\x0b\x32\x19.voltha.PonSimPortMetrics\"$\n\x14PonSimMetricsRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\x32\xc8\x02\n\x06PonSim\x12:\n\tSendFrame\x12\x13.voltha.PonSimFrame\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\rReceiveFrames\x12\x16.google.protobuf.Empty\x1a\x13.voltha.PonSimFrame\"\x00\x30\x01\x12\x43\n\rGetDeviceInfo\x12\x16.google.protobuf.Empty\x1a\x18.voltha.PonSimDeviceInfo\"\x00\x12>\n\x0fUpdateFlowTable\x12\x11.voltha.FlowTable\x1a\x16.google.protobuf.Empty\"\x00\x12;\n\x08GetStats\x12\x16.google.protobuf.Empty\x1a\x15.voltha.PonSimMetrics\"\x00\x42-Z+github.com/opencord/voltha-protos/go/volthab\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,voltha__protos_dot_openflow__13__pb2.DESCRIPTOR,])




_PONSIMONUDEVICEINFO = _descriptor.Descriptor(
  name='PonSimOnuDeviceInfo',
  full_name='voltha.PonSimOnuDeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uni_port', full_name='voltha.PonSimOnuDeviceInfo.uni_port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='voltha.PonSimOnuDeviceInfo.serial_number', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=162,
)


_PONSIMDEVICEINFO = _descriptor.Descriptor(
  name='PonSimDeviceInfo',
  full_name='voltha.PonSimDeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nni_port', full_name='voltha.PonSimDeviceInfo.nni_port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='onus', full_name='voltha.PonSimDeviceInfo.onus', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=243,
)


_FLOWTABLE = _descriptor.Descriptor(
  name='FlowTable',
  full_name='voltha.FlowTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='voltha.FlowTable.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flows', full_name='voltha.FlowTable.flows', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=314,
)


_PONSIMFRAME = _descriptor.Descriptor(
  name='PonSimFrame',
  full_name='voltha.PonSimFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='voltha.PonSimFrame.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='voltha.PonSimFrame.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_port', full_name='voltha.PonSimFrame.out_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=376,
)


_PONSIMPACKETCOUNTER = _descriptor.Descriptor(
  name='PonSimPacketCounter',
  full_name='voltha.PonSimPacketCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='voltha.PonSimPacketCounter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='voltha.PonSimPacketCounter.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=428,
)


_PONSIMPORTMETRICS = _descriptor.Descriptor(
  name='PonSimPortMetrics',
  full_name='voltha.PonSimPortMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port_name', full_name='voltha.PonSimPortMetrics.port_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packets', full_name='voltha.PonSimPortMetrics.packets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=514,
)


_PONSIMMETRICS = _descriptor.Descriptor(
  name='PonSimMetrics',
  full_name='voltha.PonSimMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='voltha.PonSimMetrics.device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='voltha.PonSimMetrics.metrics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=591,
)


_PONSIMMETRICSREQUEST = _descriptor.Descriptor(
  name='PonSimMetricsRequest',
  full_name='voltha.PonSimMetricsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='voltha.PonSimMetricsRequest.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=629,
)

_PONSIMDEVICEINFO.fields_by_name['onus'].message_type = _PONSIMONUDEVICEINFO
_FLOWTABLE.fields_by_name['flows'].message_type = voltha__protos_dot_openflow__13__pb2._OFP_FLOW_STATS
_PONSIMPORTMETRICS.fields_by_name['packets'].message_type = _PONSIMPACKETCOUNTER
_PONSIMMETRICS.fields_by_name['metrics'].message_type = _PONSIMPORTMETRICS
DESCRIPTOR.message_types_by_name['PonSimOnuDeviceInfo'] = _PONSIMONUDEVICEINFO
DESCRIPTOR.message_types_by_name['PonSimDeviceInfo'] = _PONSIMDEVICEINFO
DESCRIPTOR.message_types_by_name['FlowTable'] = _FLOWTABLE
DESCRIPTOR.message_types_by_name['PonSimFrame'] = _PONSIMFRAME
DESCRIPTOR.message_types_by_name['PonSimPacketCounter'] = _PONSIMPACKETCOUNTER
DESCRIPTOR.message_types_by_name['PonSimPortMetrics'] = _PONSIMPORTMETRICS
DESCRIPTOR.message_types_by_name['PonSimMetrics'] = _PONSIMMETRICS
DESCRIPTOR.message_types_by_name['PonSimMetricsRequest'] = _PONSIMMETRICSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PonSimOnuDeviceInfo = _reflection.GeneratedProtocolMessageType('PonSimOnuDeviceInfo', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMONUDEVICEINFO,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimOnuDeviceInfo)
  ))
_sym_db.RegisterMessage(PonSimOnuDeviceInfo)

PonSimDeviceInfo = _reflection.GeneratedProtocolMessageType('PonSimDeviceInfo', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMDEVICEINFO,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimDeviceInfo)
  ))
_sym_db.RegisterMessage(PonSimDeviceInfo)

FlowTable = _reflection.GeneratedProtocolMessageType('FlowTable', (_message.Message,), dict(
  DESCRIPTOR = _FLOWTABLE,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.FlowTable)
  ))
_sym_db.RegisterMessage(FlowTable)

PonSimFrame = _reflection.GeneratedProtocolMessageType('PonSimFrame', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMFRAME,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimFrame)
  ))
_sym_db.RegisterMessage(PonSimFrame)

PonSimPacketCounter = _reflection.GeneratedProtocolMessageType('PonSimPacketCounter', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMPACKETCOUNTER,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimPacketCounter)
  ))
_sym_db.RegisterMessage(PonSimPacketCounter)

PonSimPortMetrics = _reflection.GeneratedProtocolMessageType('PonSimPortMetrics', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMPORTMETRICS,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimPortMetrics)
  ))
_sym_db.RegisterMessage(PonSimPortMetrics)

PonSimMetrics = _reflection.GeneratedProtocolMessageType('PonSimMetrics', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMMETRICS,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimMetrics)
  ))
_sym_db.RegisterMessage(PonSimMetrics)

PonSimMetricsRequest = _reflection.GeneratedProtocolMessageType('PonSimMetricsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PONSIMMETRICSREQUEST,
  __module__ = 'voltha_protos.ponsim_pb2'
  # @@protoc_insertion_point(class_scope:voltha.PonSimMetricsRequest)
  ))
_sym_db.RegisterMessage(PonSimMetricsRequest)


DESCRIPTOR._options = None

_PONSIM = _descriptor.ServiceDescriptor(
  name='PonSim',
  full_name='voltha.PonSim',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=632,
  serialized_end=960,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendFrame',
    full_name='voltha.PonSim.SendFrame',
    index=0,
    containing_service=None,
    input_type=_PONSIMFRAME,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveFrames',
    full_name='voltha.PonSim.ReceiveFrames',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PONSIMFRAME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeviceInfo',
    full_name='voltha.PonSim.GetDeviceInfo',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PONSIMDEVICEINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFlowTable',
    full_name='voltha.PonSim.UpdateFlowTable',
    index=3,
    containing_service=None,
    input_type=_FLOWTABLE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStats',
    full_name='voltha.PonSim.GetStats',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PONSIMMETRICS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PONSIM)

DESCRIPTOR.services_by_name['PonSim'] = _PONSIM

# @@protoc_insertion_point(module_scope)
