// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voltha_protos/omci_alarm_db.proto

package omci // import "github.com/willkurk/testgodeps/go/omci"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/willkurk/testgodeps/go/common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AlarmOpenOmciEventType_OpenOmciEventType int32

const (
	AlarmOpenOmciEventType_state_change AlarmOpenOmciEventType_OpenOmciEventType = 0
)

var AlarmOpenOmciEventType_OpenOmciEventType_name = map[int32]string{
	0: "state_change",
}
var AlarmOpenOmciEventType_OpenOmciEventType_value = map[string]int32{
	"state_change": 0,
}

func (x AlarmOpenOmciEventType_OpenOmciEventType) String() string {
	return proto.EnumName(AlarmOpenOmciEventType_OpenOmciEventType_name, int32(x))
}
func (AlarmOpenOmciEventType_OpenOmciEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{6, 0}
}

type AlarmAttributeData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmAttributeData) Reset()         { *m = AlarmAttributeData{} }
func (m *AlarmAttributeData) String() string { return proto.CompactTextString(m) }
func (*AlarmAttributeData) ProtoMessage()    {}
func (*AlarmAttributeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{0}
}
func (m *AlarmAttributeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmAttributeData.Unmarshal(m, b)
}
func (m *AlarmAttributeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmAttributeData.Marshal(b, m, deterministic)
}
func (dst *AlarmAttributeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmAttributeData.Merge(dst, src)
}
func (m *AlarmAttributeData) XXX_Size() int {
	return xxx_messageInfo_AlarmAttributeData.Size(m)
}
func (m *AlarmAttributeData) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmAttributeData.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmAttributeData proto.InternalMessageInfo

func (m *AlarmAttributeData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AlarmAttributeData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AlarmInstanceData struct {
	InstanceId           uint32                `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Created              string                `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Modified             string                `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	Attributes           []*AlarmAttributeData `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AlarmInstanceData) Reset()         { *m = AlarmInstanceData{} }
func (m *AlarmInstanceData) String() string { return proto.CompactTextString(m) }
func (*AlarmInstanceData) ProtoMessage()    {}
func (*AlarmInstanceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{1}
}
func (m *AlarmInstanceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmInstanceData.Unmarshal(m, b)
}
func (m *AlarmInstanceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmInstanceData.Marshal(b, m, deterministic)
}
func (dst *AlarmInstanceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmInstanceData.Merge(dst, src)
}
func (m *AlarmInstanceData) XXX_Size() int {
	return xxx_messageInfo_AlarmInstanceData.Size(m)
}
func (m *AlarmInstanceData) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmInstanceData.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmInstanceData proto.InternalMessageInfo

func (m *AlarmInstanceData) GetInstanceId() uint32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *AlarmInstanceData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *AlarmInstanceData) GetModified() string {
	if m != nil {
		return m.Modified
	}
	return ""
}

func (m *AlarmInstanceData) GetAttributes() []*AlarmAttributeData {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type AlarmClassData struct {
	ClassId              uint32               `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Instances            []*AlarmInstanceData `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AlarmClassData) Reset()         { *m = AlarmClassData{} }
func (m *AlarmClassData) String() string { return proto.CompactTextString(m) }
func (*AlarmClassData) ProtoMessage()    {}
func (*AlarmClassData) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{2}
}
func (m *AlarmClassData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmClassData.Unmarshal(m, b)
}
func (m *AlarmClassData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmClassData.Marshal(b, m, deterministic)
}
func (dst *AlarmClassData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmClassData.Merge(dst, src)
}
func (m *AlarmClassData) XXX_Size() int {
	return xxx_messageInfo_AlarmClassData.Size(m)
}
func (m *AlarmClassData) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmClassData.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmClassData proto.InternalMessageInfo

func (m *AlarmClassData) GetClassId() uint32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *AlarmClassData) GetInstances() []*AlarmInstanceData {
	if m != nil {
		return m.Instances
	}
	return nil
}

type AlarmManagedEntity struct {
	ClassId              uint32   `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmManagedEntity) Reset()         { *m = AlarmManagedEntity{} }
func (m *AlarmManagedEntity) String() string { return proto.CompactTextString(m) }
func (*AlarmManagedEntity) ProtoMessage()    {}
func (*AlarmManagedEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{3}
}
func (m *AlarmManagedEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmManagedEntity.Unmarshal(m, b)
}
func (m *AlarmManagedEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmManagedEntity.Marshal(b, m, deterministic)
}
func (dst *AlarmManagedEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmManagedEntity.Merge(dst, src)
}
func (m *AlarmManagedEntity) XXX_Size() int {
	return xxx_messageInfo_AlarmManagedEntity.Size(m)
}
func (m *AlarmManagedEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmManagedEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmManagedEntity proto.InternalMessageInfo

func (m *AlarmManagedEntity) GetClassId() uint32 {
	if m != nil {
		return m.ClassId
	}
	return 0
}

func (m *AlarmManagedEntity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AlarmMessageType struct {
	MessageType          uint32   `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmMessageType) Reset()         { *m = AlarmMessageType{} }
func (m *AlarmMessageType) String() string { return proto.CompactTextString(m) }
func (*AlarmMessageType) ProtoMessage()    {}
func (*AlarmMessageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{4}
}
func (m *AlarmMessageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmMessageType.Unmarshal(m, b)
}
func (m *AlarmMessageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmMessageType.Marshal(b, m, deterministic)
}
func (dst *AlarmMessageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmMessageType.Merge(dst, src)
}
func (m *AlarmMessageType) XXX_Size() int {
	return xxx_messageInfo_AlarmMessageType.Size(m)
}
func (m *AlarmMessageType) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmMessageType.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmMessageType proto.InternalMessageInfo

func (m *AlarmMessageType) GetMessageType() uint32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

type AlarmDeviceData struct {
	DeviceId             string                `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Created              string                `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	LastAlarmSequence    uint32                `protobuf:"varint,3,opt,name=last_alarm_sequence,json=lastAlarmSequence,proto3" json:"last_alarm_sequence,omitempty"`
	LastSyncTime         string                `protobuf:"bytes,4,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	Version              uint32                `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Classes              []*AlarmClassData     `protobuf:"bytes,6,rep,name=classes,proto3" json:"classes,omitempty"`
	ManagedEntities      []*AlarmManagedEntity `protobuf:"bytes,7,rep,name=managed_entities,json=managedEntities,proto3" json:"managed_entities,omitempty"`
	MessageTypes         []*AlarmMessageType   `protobuf:"bytes,8,rep,name=message_types,json=messageTypes,proto3" json:"message_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AlarmDeviceData) Reset()         { *m = AlarmDeviceData{} }
func (m *AlarmDeviceData) String() string { return proto.CompactTextString(m) }
func (*AlarmDeviceData) ProtoMessage()    {}
func (*AlarmDeviceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{5}
}
func (m *AlarmDeviceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmDeviceData.Unmarshal(m, b)
}
func (m *AlarmDeviceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmDeviceData.Marshal(b, m, deterministic)
}
func (dst *AlarmDeviceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmDeviceData.Merge(dst, src)
}
func (m *AlarmDeviceData) XXX_Size() int {
	return xxx_messageInfo_AlarmDeviceData.Size(m)
}
func (m *AlarmDeviceData) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmDeviceData.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmDeviceData proto.InternalMessageInfo

func (m *AlarmDeviceData) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AlarmDeviceData) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *AlarmDeviceData) GetLastAlarmSequence() uint32 {
	if m != nil {
		return m.LastAlarmSequence
	}
	return 0
}

func (m *AlarmDeviceData) GetLastSyncTime() string {
	if m != nil {
		return m.LastSyncTime
	}
	return ""
}

func (m *AlarmDeviceData) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *AlarmDeviceData) GetClasses() []*AlarmClassData {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *AlarmDeviceData) GetManagedEntities() []*AlarmManagedEntity {
	if m != nil {
		return m.ManagedEntities
	}
	return nil
}

func (m *AlarmDeviceData) GetMessageTypes() []*AlarmMessageType {
	if m != nil {
		return m.MessageTypes
	}
	return nil
}

type AlarmOpenOmciEventType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlarmOpenOmciEventType) Reset()         { *m = AlarmOpenOmciEventType{} }
func (m *AlarmOpenOmciEventType) String() string { return proto.CompactTextString(m) }
func (*AlarmOpenOmciEventType) ProtoMessage()    {}
func (*AlarmOpenOmciEventType) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{6}
}
func (m *AlarmOpenOmciEventType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmOpenOmciEventType.Unmarshal(m, b)
}
func (m *AlarmOpenOmciEventType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmOpenOmciEventType.Marshal(b, m, deterministic)
}
func (dst *AlarmOpenOmciEventType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmOpenOmciEventType.Merge(dst, src)
}
func (m *AlarmOpenOmciEventType) XXX_Size() int {
	return xxx_messageInfo_AlarmOpenOmciEventType.Size(m)
}
func (m *AlarmOpenOmciEventType) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmOpenOmciEventType.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmOpenOmciEventType proto.InternalMessageInfo

type AlarmOpenOmciEvent struct {
	Type                 AlarmOpenOmciEventType_OpenOmciEventType `protobuf:"varint,1,opt,name=type,proto3,enum=alarm.AlarmOpenOmciEventType_OpenOmciEventType" json:"type,omitempty"`
	Data                 string                                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *AlarmOpenOmciEvent) Reset()         { *m = AlarmOpenOmciEvent{} }
func (m *AlarmOpenOmciEvent) String() string { return proto.CompactTextString(m) }
func (*AlarmOpenOmciEvent) ProtoMessage()    {}
func (*AlarmOpenOmciEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_omci_alarm_db_f3563993e5a0e68b, []int{7}
}
func (m *AlarmOpenOmciEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlarmOpenOmciEvent.Unmarshal(m, b)
}
func (m *AlarmOpenOmciEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlarmOpenOmciEvent.Marshal(b, m, deterministic)
}
func (dst *AlarmOpenOmciEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlarmOpenOmciEvent.Merge(dst, src)
}
func (m *AlarmOpenOmciEvent) XXX_Size() int {
	return xxx_messageInfo_AlarmOpenOmciEvent.Size(m)
}
func (m *AlarmOpenOmciEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AlarmOpenOmciEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AlarmOpenOmciEvent proto.InternalMessageInfo

func (m *AlarmOpenOmciEvent) GetType() AlarmOpenOmciEventType_OpenOmciEventType {
	if m != nil {
		return m.Type
	}
	return AlarmOpenOmciEventType_state_change
}

func (m *AlarmOpenOmciEvent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*AlarmAttributeData)(nil), "alarm.AlarmAttributeData")
	proto.RegisterType((*AlarmInstanceData)(nil), "alarm.AlarmInstanceData")
	proto.RegisterType((*AlarmClassData)(nil), "alarm.AlarmClassData")
	proto.RegisterType((*AlarmManagedEntity)(nil), "alarm.AlarmManagedEntity")
	proto.RegisterType((*AlarmMessageType)(nil), "alarm.AlarmMessageType")
	proto.RegisterType((*AlarmDeviceData)(nil), "alarm.AlarmDeviceData")
	proto.RegisterType((*AlarmOpenOmciEventType)(nil), "alarm.AlarmOpenOmciEventType")
	proto.RegisterType((*AlarmOpenOmciEvent)(nil), "alarm.AlarmOpenOmciEvent")
	proto.RegisterEnum("alarm.AlarmOpenOmciEventType_OpenOmciEventType", AlarmOpenOmciEventType_OpenOmciEventType_name, AlarmOpenOmciEventType_OpenOmciEventType_value)
}

func init() {
	proto.RegisterFile("voltha_protos/omci_alarm_db.proto", fileDescriptor_omci_alarm_db_f3563993e5a0e68b)
}

var fileDescriptor_omci_alarm_db_f3563993e5a0e68b = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x6e, 0x20, 0x81, 0x30, 0x49, 0x20, 0x6c, 0xff, 0x16, 0x24, 0x24, 0x6a, 0xb5, 0x28, 0xa7,
	0x44, 0xa2, 0x57, 0xa4, 0x96, 0x00, 0x95, 0xa8, 0x54, 0xa1, 0x1a, 0x4e, 0xbd, 0x58, 0x1b, 0x7b,
	0xea, 0xac, 0xf0, 0xae, 0x53, 0xef, 0x26, 0x55, 0x2e, 0xbd, 0xf5, 0xa1, 0xfa, 0x10, 0xbc, 0x44,
	0x4f, 0x7d, 0x02, 0xce, 0x95, 0xc7, 0x76, 0x62, 0xcb, 0x52, 0xd5, 0x9b, 0xbf, 0x99, 0x6f, 0xbe,
	0x99, 0x9d, 0x6f, 0x64, 0x78, 0xb5, 0x88, 0x23, 0x3b, 0x15, 0xde, 0x2c, 0x89, 0x6d, 0x6c, 0x46,
	0xb1, 0xf2, 0xa5, 0x27, 0x22, 0x91, 0x28, 0x2f, 0x98, 0x0c, 0x29, 0xc8, 0x5a, 0x84, 0x0f, 0x79,
	0x95, 0xa9, 0xd0, 0x8a, 0x8c, 0xe0, 0x5c, 0x01, 0x3b, 0x4f, 0x29, 0xe7, 0xd6, 0x26, 0x72, 0x32,
	0xb7, 0x78, 0x29, 0xac, 0x60, 0x07, 0xd0, 0xd4, 0x42, 0x21, 0x6f, 0x1c, 0x37, 0x06, 0x3b, 0xe3,
	0xd6, 0x9f, 0xc7, 0x87, 0xa3, 0x86, 0x4b, 0x21, 0xf6, 0x0c, 0x5a, 0x0b, 0x11, 0xcd, 0x91, 0x6f,
	0xa4, 0x39, 0x37, 0x03, 0xce, 0xaf, 0x06, 0xec, 0x93, 0xce, 0xb5, 0x36, 0x56, 0x68, 0x3f, 0x93,
	0x39, 0x81, 0x8e, 0xcc, 0xb1, 0x27, 0x03, 0x52, 0xeb, 0x15, 0x6a, 0x50, 0x64, 0xae, 0x03, 0xc6,
	0x61, 0xdb, 0x4f, 0x50, 0x58, 0x0c, 0x72, 0xd5, 0x02, 0xb2, 0x43, 0x68, 0xab, 0x38, 0x90, 0x5f,
	0x25, 0x06, 0x7c, 0x93, 0x52, 0x2b, 0xcc, 0x3e, 0x00, 0x88, 0x62, 0x6a, 0xc3, 0x9b, 0xc7, 0x9b,
	0x83, 0xce, 0xe9, 0xc1, 0x90, 0x1e, 0x3c, 0xac, 0xbf, 0x69, 0xdc, 0xf9, 0xfd, 0xf8, 0x70, 0xb4,
	0x95, 0x3d, 0xcc, 0x2d, 0x55, 0x3a, 0x3f, 0x60, 0x97, 0xe8, 0x17, 0x91, 0x30, 0x86, 0xe6, 0x3e,
	0x86, 0xb6, 0x9f, 0x82, 0xda, 0xd0, 0xdb, 0x14, 0xbe, 0x0e, 0xd8, 0x47, 0xd8, 0x29, 0xe6, 0x37,
	0x7c, 0x83, 0x5a, 0xf3, 0x72, 0xeb, 0xf2, 0x1a, 0xc6, 0x2c, 0xed, 0xdc, 0xab, 0xec, 0xc2, 0x5d,
	0x97, 0x3b, 0x9f, 0x73, 0x0b, 0x3e, 0x09, 0x2d, 0x42, 0x0c, 0xae, 0xb4, 0x95, 0x76, 0xf9, 0x1f,
	0x33, 0x14, 0x26, 0x6d, 0xd4, 0x4c, 0x72, 0xce, 0xa0, 0x9f, 0x49, 0xa2, 0x31, 0x22, 0xc4, 0xbb,
	0xe5, 0x0c, 0xd9, 0x00, 0xba, 0x2a, 0x83, 0x9e, 0x5d, 0xce, 0xb0, 0x2a, 0xda, 0x51, 0x6b, 0xa6,
	0xf3, 0x73, 0x13, 0xf6, 0xa8, 0xfc, 0x12, 0x17, 0x32, 0xb7, 0xd2, 0x81, 0x9d, 0x80, 0x50, 0x31,
	0xcf, 0xaa, 0x63, 0x3b, 0x8b, 0xff, 0xd3, 0xc6, 0x21, 0x3c, 0x8d, 0x84, 0xb1, 0xf9, 0x75, 0x1a,
	0xfc, 0x36, 0x47, 0xed, 0x23, 0x39, 0xda, 0x73, 0xf7, 0xd3, 0x14, 0xf5, 0xbb, 0xcd, 0x13, 0xec,
	0x35, 0xec, 0x12, 0xdf, 0x2c, 0xb5, 0xef, 0x59, 0xa9, 0x90, 0x37, 0x49, 0xb0, 0x9b, 0x46, 0x6f,
	0x97, 0xda, 0xbf, 0x93, 0x0a, 0xd3, 0x7e, 0x0b, 0x4c, 0x8c, 0x8c, 0x35, 0x6f, 0x91, 0x52, 0x01,
	0xd9, 0x7b, 0xc8, 0xb6, 0x84, 0x86, 0x6f, 0x91, 0x39, 0xcf, 0xcb, 0xe6, 0xac, 0x8c, 0x1e, 0xef,
	0xa5, 0xce, 0xc0, 0x7a, 0xd3, 0x6e, 0x51, 0xc6, 0x2e, 0xa1, 0xaf, 0x32, 0x3f, 0x3c, 0x4c, 0x0d,
	0x91, 0x68, 0xf8, 0x76, 0xfd, 0xc4, 0x2a, 0x9e, 0xb9, 0x7b, 0xaa, 0x04, 0x25, 0x1a, 0x76, 0x06,
	0xbd, 0xf2, 0xce, 0x0d, 0x6f, 0x93, 0xc4, 0xcb, 0x8a, 0xc4, 0x7a, 0xf3, 0x6e, 0xb7, 0x64, 0x83,
	0x71, 0xde, 0xc1, 0x0b, 0x62, 0xdc, 0xcc, 0x50, 0xdf, 0x28, 0x5f, 0x5e, 0x2d, 0x50, 0x5b, 0x72,
	0xe8, 0x0d, 0xec, 0xd7, 0x82, 0xac, 0x0f, 0x5d, 0x63, 0x85, 0x45, 0xcf, 0x9f, 0x0a, 0x1d, 0x62,
	0xff, 0x89, 0xa3, 0xf2, 0xcb, 0xaa, 0x70, 0xd9, 0x05, 0x34, 0x57, 0x07, 0xb0, 0x7b, 0x3a, 0x2a,
	0xcf, 0x52, 0x13, 0x1d, 0xd6, 0x22, 0x2e, 0x15, 0x33, 0x06, 0xcd, 0x40, 0x58, 0x91, 0x1b, 0x4d,
	0xdf, 0xe3, 0xc1, 0x97, 0x93, 0x50, 0xda, 0xe9, 0x7c, 0x32, 0xf4, 0x63, 0x35, 0xfa, 0x2e, 0xa3,
	0xe8, 0x7e, 0x9e, 0xdc, 0x8f, 0x2c, 0x1a, 0x1b, 0xc6, 0x01, 0xce, 0xcc, 0x28, 0x8c, 0xe9, 0x2f,
	0x35, 0xd9, 0xa2, 0x9f, 0xcf, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x34, 0xef, 0x9d,
	0xc2, 0x04, 0x00, 0x00,
}
